spring:
  application:
    name: myapp-jsp
  mvc:
    view:
      prefix: classpath:/WEB-INF/views/
      suffix: .jsp
  web:
    resources:
      static-locations:
      - classpath:/
server:
  port: 8888